# Site settings
title: Patrocinador Estratégico
description: Contribuimos a Incrementar las Mejores Iniciativas Sociales.
keywords: agente, promotor, eventos, editorial, agencia, arte, gestión, cultura
author: tdrid
url: "https://lucfreelance.github.io/tdrid/"
