# Site settings
title: Trozos De Realidad - Digital Tricks
description: Where to find a bit more service tan desired
keywords: Digital, Services, Assistance
author: Lucfreelance
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lucfreelance.github.io/tdrdt/"
