# Site settings
title: Trozos De Realidad Digital Tier
description: In Trozos De Realidad Digital Tier "we create our own system".
keywords: Advertising, Publishing, Agency
author: Lucfreelance
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lucfreelance.github.io/tdrdt/"
