# Site settings
title: Patrocinador Estratégico
description: Contribuimos a Incrementar las Mejores Iniciativas Sociales.
keywords: Agente Publicitario, Promotora de Eventos, Editorial digital, Agencia de Artistas, Gestión Cultural, Patrocinador Estratégico
author: tdrid
url: "https://lucfreelance.github.io/tdrdt/"
